#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond
# You must use kill

# Get the PID of the process
PID=$(pgrep -f 4-to_infinity_and_beyond)

# If the process is found, kill it
if [ ! -z "$PID" ]
then
	kill $PID
fi
