#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but on the 9th displaya "Hi"
i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
